# Site settings
title: Kleszcz's Dev Blog
header-img: img/home-bg.jpg
email: jankleszcz@gmail.com
copyright_name: kleszcz.github.io
description: "My own little dev blog"
baseurl: "/blog"
url: "http://kleszcz.github.io"
twitter_username: jan.kleszczynski
github_username:  kleszcz
facebook_username:
email_username:  jankleszcz@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
